CPSC411 – Assignment 2
======================

[quote]
____
Write an Objective-C or C program that assists you in answering the following
question.

Given the file `CS411SampleCode/sample_data/words.zip` in the course GitHub
repository, find all the anagrams. What are the words that form the largest set
of anagrams given the words in the file? How long does your program take to
calculate the answer in seconds? What kind of CPU are you using?

(If your program takes longer than 5 seconds, then please rewrite your
program.)

Instructions will be posted towards the due date regarding how to submit your
answer.

If your answer is correct and the code executes correctly, you will receive
full credit. If your answer is incorrect you will receive no credit. If your
code does not execute correctly or if nothing is submitted you will receive no
credit.

There are 100 points possible.
____

Different versions
------------------
For fun I created a couple of different versions in different languages.

Go:

----
The largest number of anagrams is 11
[angor argon goran grano groan nagor Orang orang organ rogan Ronga]

real    0m0.371s
user    0m0.339s
sys     0m0.028s
----

PHP:

----
The largest number of anagrams is 11
[angor argon goran grano groan nagor Orang orang organ rogan Ronga]

real    0m8.760s
user    0m8.594s
sys     0m0.163s
----

License
-------
BSD, check the LICENSE file.
